In [4]:
2+1

3

1. this
2. is
3. an
    1. outline
    2. with
    3. sub outline

In [5]:
import pandas as pd

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
iris = pd.read_csv(url)
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic = pd.read_csv(url)
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
wine = pd.read_csv(url, sep=';')
wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [8]:
url = "https://raw.githubusercontent.com/allisonhorst/palmerpenguins/master/inst/extdata/penguins.csv"
penguins = pd.read_csv(url)
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [9]:
url = "https://raw.githubusercontent.com/ardhiraka/PFDS_sources/master/world-happiness-report-2021.csv"
happiness = pd.read_csv(url)
happiness.head()

HTTPError: HTTP Error 404: Not Found

In [10]:
url = "https://raw.githubusercontent.com/hadley/data-baby-names/master/baby-names.csv"
baby_names = pd.read_csv(url)
baby_names.info()  # This will show you if there are any missing data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 258000 entries, 0 to 257999
Data columns (total 4 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   year     258000 non-null  int64
 1   name     258000 non-null  object
 2   percent  258000 non-null  float64
 3   sex      258000 non-null  object
dtypes: float64(1), int64(1), object(2)
memory usage: 7.9+ MB

In [11]:
# Check the number of missing values per column
missing_counts = baby_names.isnull().sum()

# Check the proportion of missing values per column
missing_proportion = baby_names.isnull().mean()

print("Missing Values Count:\n", missing_counts)
print("\nProportion of Missing Values:\n", missing_proportion)

Missing Values Count:
 year       0
name       0
percent    0
sex        0
dtype: int64

Proportion of Missing Values:
 year       0.0
name       0.0
percent    0.0
sex        0.0
dtype: float64

In [12]:
# Load the dataset
url = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"
housing = pd.read_csv(url)

# Check for missing data
print(housing.isnull().sum())

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

# Summary of ChatBot Session

## https://chatgpt.com/share/a20cb358-f44f-4628-b9ca-191b00fa60ce

Certainly! Here’s a summary of our interaction:

---

### Summary of Interaction

**Objective:** 
To find and work with datasets that are publicly available and to explore their characteristics, including the presence of missing data.

**Tasks and Findings:**

1. **Dataset Selection:**
   - **Initial Request:** The user sought datasets that are funny, amusing, or otherwise interesting.
   - **Recommendations:** Provided datasets including The Office US Scripts, Pokemon, Star Wars Movie Scripts, Global Food Consumption, Wine Reviews, World Happiness Report, Bizarre Holidays, and the Titanic Dataset. Noted that some links were broken or incorrect.

2. **Handling Missing Data:**
   - **Datasets Suggested:** The Titanic Dataset, US Baby Names Dataset, and other options.
   - **Outcome:** The Titanic Dataset and US Baby Names Dataset were checked for missing data, but both were found to be complete. The Boston Housing dataset was suggested next, but it also did not contain missing values.

3. **Final Dataset Choice:**
   - The user decided to use the Housing Prices Dataset, also known as the Boston Housing dataset, despite its lack of missing values. It was confirmed that this dataset does not have missing values.

4. **Evaluation and Feedback:**
   - The user tested the responses on several criteria including dataset characteristics, the accuracy of missing data identification, and working URLs.
   - **Feedback Provided:** The initial dataset recommendations did not fully meet expectations for being funny or amusing. The datasets with missing data were inaccurately identified. URLs for downloading datasets were mostly correct but had issues initially.

**Conclusion:**
The interaction involved finding suitable datasets, checking for missing data, and evaluating the quality and accuracy of the provided information. The user’s feedback highlighted areas for improvement in identifying datasets with missing data and ensuring accurate and working links.

---

Feel free to adjust or expand on any details based on the specific requirements of your assignment!